name: flutter_t_store
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

# ---------- PACKAGES ---------- #
dependencies:
  flutter:
    sdk: flutter

  # Utility
  cached_network_image: ^3.3.1
  connectivity_plus: ^6.0.3
  flutter_native_splash: ^2.4.0
  http: ^1.2.1
  image_picker: ^1.1.1
  intl: ^0.19.0
  logger: ^2.2.0
  lottie: ^3.1.0
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.6

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

  # State Managment
  get: ^4.6.6
  get_storage: ^2.1.1

  # firebase
  cloud_firestore: ^4.17.2
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4

  # product-specific
  capped_progress_indicator: ^0.0.2
  carousel_slider: ^4.2.1
  flutter_rating_bar: ^4.0.1
  readmore: ^3.0.0

# ---------- DEV ONLY PACKAGES ---------- #

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.2

# ---------- ./ PACKAGES END ---------- #

flutter:
  uses-material-design: true

# ---------- LOCAL FILES ---------- #

  # ---------- ASSETS ---------- #
  assets:
    - assets/logos/
    - assets/icons/
    - assets/icons/categories/
    - assets/images/on_boarding_images/
    - assets/images/animations/
    - assets/images/banners/
    - assets/images/products/
    - assets/images/content/
    - assets/images/reviews/
    - assets/icons/payment_methods/

  # ---------- FONTS ---------- #
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

# ---------- ./ LOCAL FILES END ---------- #
