// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQPS0Ykzt1xOHpEqrHtqtMIyCh_-_J8Rg',
    appId: '1:729238111991:web:1de3a98d363d54725eb5f2',
    messagingSenderId: '729238111991',
    projectId: 'ecommeceapp-94998',
    authDomain: 'ecommeceapp-94998.firebaseapp.com',
    storageBucket: 'ecommeceapp-94998.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBne7oYRbK0Y9mMUpErRqRCBL5-5jgBLAo',
    appId: '1:729238111991:android:cc20e77e2eee13e05eb5f2',
    messagingSenderId: '729238111991',
    projectId: 'ecommeceapp-94998',
    storageBucket: 'ecommeceapp-94998.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVauQtCoN4joADsLo0SQIhZD5-sIbOiTU',
    appId: '1:729238111991:ios:17dac7892e406f8b5eb5f2',
    messagingSenderId: '729238111991',
    projectId: 'ecommeceapp-94998',
    storageBucket: 'ecommeceapp-94998.appspot.com',
    androidClientId: '729238111991-khm0np2dc94dgklmti719ogn8s34ga74.apps.googleusercontent.com',
    iosClientId: '729238111991-c87ghusrsdjdfelvg7cjdov7rr965kar.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQPS0Ykzt1xOHpEqrHtqtMIyCh_-_J8Rg',
    appId: '1:729238111991:web:53769e588bc459965eb5f2',
    messagingSenderId: '729238111991',
    projectId: 'ecommeceapp-94998',
    authDomain: 'ecommeceapp-94998.firebaseapp.com',
    storageBucket: 'ecommeceapp-94998.appspot.com',
  );

}